export const NAME = 'house';
export const ROOMS_SCENE_KEY = `${NAME}/ROOMS_SCENE_KEY`;
export const CATEGORIES_SCENE_KEY = `${NAME}/CATEGORIES_SCENE_KEY`;
export const SERVER_STORAGE_KEY = `${NAME}/SERVER_STORAGE_KEY`;
export const ONBOARDING_SERVER_FORM_NAME = `${NAME}/ONBOARDING_SERVER_FORM_NAME`;
export const DRAFT_ROOM_ID = '__draft';
export const ROOM_FORM_NAME = `${NAME}/ROOM_FORM_NAME`;
