export const NAME = 'onboarding';
export const LOADING_SCENE_KEY = `${NAME}/LOADING_SCENE`;
export const ONBOARDING_HOME_SCENE_KEY = `${NAME}/ONBOARDING_HOME_SCENE_KEY`;
export const ONBOARDING_SERVER_SCENE_KEY = `${NAME}/ONBOARDING_SERVER_SCENE_KEY`;
